### ISSUE TITLE
Messagehub In node should remove consumer instance and clean up when node close/redeployed

### ISSUE THREAD

**Issue by chanjc** [luiselizondo/node-red-contrib-messagehub-node#1]
Hi Luise,

There is some issues if I re-configure the node and it can't reflect the changes and keep throwing out errors in the console. I do some minor fixes on the code for:
- remove consumer instance and some clean up if the flow is redeployed or node-red restarted.
- error handling 
  Attached the modified code and hope it helps.
  [messagehub.zip](https://github.com/luiselizondo/node-red-contrib-messagehub-node/files/463170/messagehub.zip)

Regards,
Jen Chyi, Chan
chanjch@my.ibm.com

**Comment by luiselizondo** [comment]
Hi Jen, I created this module when I was an IBMer. I left the company but I think the Message Hub still maintains this project somewhere. Can you please confirm this by speaking to Simon Clark or @hindessm ? If not, I will be gladly add you as maintainer. 

One more thing. Can you create a commit and a PR? It will be easier for me to merge your code changes.

**Comment by chanjc** [comment]
Hi Luise,

Thanks for the reply!
I will drop a mail to Simon & Hindessm about this. But I'm not from the messagehub team. Just happened that I need to integrate with messagehub in node-red and I found your contrib!

I had created a fork - PR and please review. Thanks.
